// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
  // TelemPoint
  //

  inline
  access::object_traits< ::TelemPoint >::id_type
  access::object_traits< ::TelemPoint >::
  id (const object_type& o)
  {
    return o.id;
  }

  inline
  void access::object_traits< ::TelemPoint >::
  callback (database& db, object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  inline
  void access::object_traits< ::TelemPoint >::
  callback (database& db, const object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  // MasterPoint
  //

  inline
  access::object_traits< ::MasterPoint >::id_type
  access::object_traits< ::MasterPoint >::
  id (const object_type& o)
  {
    return object_traits< ::TelemPoint >::id (o);
  }

  inline
  void access::object_traits< ::MasterPoint >::
  callback (database& db, object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  inline
  void access::object_traits< ::MasterPoint >::
  callback (database& db, const object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  // SlavePoint
  //

  inline
  access::object_traits< ::SlavePoint >::id_type
  access::object_traits< ::SlavePoint >::
  id (const object_type& o)
  {
    return o.id;
  }

  inline
  void access::object_traits< ::SlavePoint >::
  callback (database& db, object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }

  inline
  void access::object_traits< ::SlavePoint >::
  callback (database& db, const object_type& x, callback_event e)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (x);
    ODB_POTENTIALLY_UNUSED (e);
  }
}

#include <odb/details/unique-ptr.hxx>

namespace odb
{
  // TelemPoint
  //

  inline
  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  load_ (statements_type& sts,
         object_type& obj,
         bool)
  {
    ODB_POTENTIALLY_UNUSED (sts);
    ODB_POTENTIALLY_UNUSED (obj);
  }

  // MasterPoint
  //

  inline
  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    object_traits_impl< ::TelemPoint, id_sqlite >::bind (b, i);
  }

  inline
  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    object_traits_impl< ::TelemPoint, id_sqlite >::init (i, id);
  }

  inline
  bool access::object_traits_impl< ::MasterPoint, id_sqlite >::
  check_version (const std::size_t* v, const image_type& i)
  {
    return 
      v[0UL] != i.version ||
      v[1UL] != i.base->version;
  }

  inline
  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  update_version (std::size_t* v, const image_type& i, sqlite::binding* b)
  {
    v[0UL] = i.version;
    v[1UL] = i.base->version;
    b[0UL].version++;
    b[1UL].version++;
  }

  // SlavePoint
  //

  inline
  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  erase (database& db, const object_type& obj)
  {
    callback (db, obj, callback_event::pre_erase);
    erase (db, id (obj));
    callback (db, obj, callback_event::post_erase);
  }

  inline
  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  load_ (statements_type& sts,
         object_type& obj,
         bool)
  {
    ODB_POTENTIALLY_UNUSED (sts);
    ODB_POTENTIALLY_UNUSED (obj);
  }
}

