// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "models-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy
#include <typeinfo>

#include <odb/polymorphic-map.hxx>
#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/polymorphic-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>
#include <odb/sqlite/polymorphic-object-result.hxx>

namespace odb
{
  // TelemPoint
  //

  struct access::object_traits_impl< ::TelemPoint, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::TelemPoint, id_sqlite >::id_type
  access::object_traits_impl< ::TelemPoint, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::TelemPoint, id_sqlite >::id_type
  access::object_traits_impl< ::TelemPoint, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::TelemPoint, id_sqlite >::discriminator_type
  access::object_traits_impl< ::TelemPoint, id_sqlite >::
  discriminator (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    discriminator_type d;
    {
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        d,
        i.typeid_value,
        i.typeid_size,
        i.typeid_null);
    }

    return d;
  }

  bool access::object_traits_impl< ::TelemPoint, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = false;

    // typeid_
    //
    if (t[1UL])
    {
      i.typeid_value.capacity (i.typeid_size);
      grew = true;
    }

    // name
    //
    if (t[2UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // register_address
    //
    if (t[3UL])
    {
      i.register_address_value.capacity (i.register_address_size);
      grew = true;
    }

    // data_type
    //
    t[4UL] = false;

    // value_type
    //
    t[5UL] = false;

    // bool_value
    //
    t[6UL] = false;

    // int_value
    //
    t[7UL] = false;

    // float_value
    //
    t[8UL] = false;

    // timestamp
    //
    t[9UL] = false;

    // unit
    //
    if (t[10UL])
    {
      i.unit_value.capacity (i.unit_size);
      grew = true;
    }

    // request_flag
    //
    t[11UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // typeid_
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::image_traits<
        ::std::string,
        sqlite::id_text>::bind_value;
      b[n].buffer = i.typeid_value.data ();
      b[n].size = &i.typeid_size;
      b[n].capacity = i.typeid_value.capacity ();
      b[n].is_null = &i.typeid_null;
      n++;
    }

    // name
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.name_value.data ();
    b[n].size = &i.name_size;
    b[n].capacity = i.name_value.capacity ();
    b[n].is_null = &i.name_null;
    n++;

    // register_address
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.register_address_value.data ();
    b[n].size = &i.register_address_size;
    b[n].capacity = i.register_address_value.capacity ();
    b[n].is_null = &i.register_address_null;
    n++;

    // data_type
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.data_type_value;
    b[n].is_null = &i.data_type_null;
    n++;

    // value_type
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.value_type_value;
    b[n].is_null = &i.value_type_null;
    n++;

    // bool_value
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.bool_value_value;
    b[n].is_null = &i.bool_value_null;
    n++;

    // int_value
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.int_value_value;
    b[n].is_null = &i.int_value_null;
    n++;

    // float_value
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.float_value_value;
    b[n].is_null = &i.float_value_null;
    n++;

    // timestamp
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.timestamp_value;
    b[n].is_null = &i.timestamp_null;
    n++;

    // unit
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.unit_value.data ();
    b[n].size = &i.unit_size;
    b[n].capacity = i.unit_value.capacity ();
    b[n].is_null = &i.unit_null;
    n++;

    // request_flag
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.request_flag_value;
    b[n].is_null = &i.request_flag_null;
    n++;
  }

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::TelemPoint, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      ::int64_t const& v =
        o.id;

      bool is_null (false);
      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        v);
      i.id_null = is_null;
    }

    // typeid_
    //
    if (sk == statement_insert)
    {
      const info_type& di (map->find (typeid (o)));

      bool is_null (false);
      std::size_t cap (i.typeid_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.typeid_value,
        i.typeid_size,
        is_null,
        di.discriminator);
      i.typeid_null = is_null;
      grew = grew || (cap != i.typeid_value.capacity ());
    }

    // name
    //
    {
      ::std::string const& v =
        o.name;

      bool is_null (false);
      std::size_t cap (i.name_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.name_value,
        i.name_size,
        is_null,
        v);
      i.name_null = is_null;
      grew = grew || (cap != i.name_value.capacity ());
    }

    // register_address
    //
    {
      ::std::string const& v =
        o.register_address;

      bool is_null (false);
      std::size_t cap (i.register_address_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.register_address_value,
        i.register_address_size,
        is_null,
        v);
      i.register_address_null = is_null;
      grew = grew || (cap != i.register_address_value.capacity ());
    }

    // data_type
    //
    {
      ::TelemDataType const& v =
        o.data_type;

      bool is_null (false);
      sqlite::value_traits<
          ::TelemDataType,
          sqlite::id_integer >::set_image (
        i.data_type_value,
        is_null,
        v);
      i.data_type_null = is_null;
    }

    // value_type
    //
    {
      ::ValueType const& v =
        o.value_type;

      bool is_null (false);
      sqlite::value_traits<
          ::ValueType,
          sqlite::id_integer >::set_image (
        i.value_type_value,
        is_null,
        v);
      i.value_type_null = is_null;
    }

    // bool_value
    //
    {
      bool const& v =
        o.bool_value;

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.bool_value_value,
        is_null,
        v);
      i.bool_value_null = is_null;
    }

    // int_value
    //
    {
      ::int32_t const& v =
        o.int_value;

      bool is_null (false);
      sqlite::value_traits<
          ::int32_t,
          sqlite::id_integer >::set_image (
        i.int_value_value,
        is_null,
        v);
      i.int_value_null = is_null;
    }

    // float_value
    //
    {
      float const& v =
        o.float_value;

      bool is_null (false);
      sqlite::value_traits<
          float,
          sqlite::id_real >::set_image (
        i.float_value_value,
        is_null,
        v);
      i.float_value_null = is_null;
    }

    // timestamp
    //
    {
      ::time_t const& v =
        o.timestamp;

      bool is_null (false);
      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_image (
        i.timestamp_value,
        is_null,
        v);
      i.timestamp_null = is_null;
    }

    // unit
    //
    {
      ::std::string const& v =
        o.unit;

      bool is_null (true);
      std::size_t cap (i.unit_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.unit_value,
        i.unit_size,
        is_null,
        v);
      i.unit_null = is_null;
      grew = grew || (cap != i.unit_value.capacity ());
    }

    // request_flag
    //
    {
      int const& v =
        o.request_flag;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.request_flag_value,
        is_null,
        v);
      i.request_flag_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      ::int64_t& v =
        o.id;

      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // name
    //
    {
      ::std::string& v =
        o.name;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.name_value,
        i.name_size,
        i.name_null);
    }

    // register_address
    //
    {
      ::std::string& v =
        o.register_address;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.register_address_value,
        i.register_address_size,
        i.register_address_null);
    }

    // data_type
    //
    {
      ::TelemDataType& v =
        o.data_type;

      sqlite::value_traits<
          ::TelemDataType,
          sqlite::id_integer >::set_value (
        v,
        i.data_type_value,
        i.data_type_null);
    }

    // value_type
    //
    {
      ::ValueType& v =
        o.value_type;

      sqlite::value_traits<
          ::ValueType,
          sqlite::id_integer >::set_value (
        v,
        i.value_type_value,
        i.value_type_null);
    }

    // bool_value
    //
    {
      bool& v =
        o.bool_value;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.bool_value_value,
        i.bool_value_null);
    }

    // int_value
    //
    {
      ::int32_t& v =
        o.int_value;

      sqlite::value_traits<
          ::int32_t,
          sqlite::id_integer >::set_value (
        v,
        i.int_value_value,
        i.int_value_null);
    }

    // float_value
    //
    {
      float& v =
        o.float_value;

      sqlite::value_traits<
          float,
          sqlite::id_real >::set_value (
        v,
        i.float_value_value,
        i.float_value_null);
    }

    // timestamp
    //
    {
      ::time_t& v =
        o.timestamp;

      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_value (
        v,
        i.timestamp_value,
        i.timestamp_null);
    }

    // unit
    //
    {
      ::std::string& v =
        o.unit;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.unit_value,
        i.unit_size,
        i.unit_null);
    }

    // request_flag
    //
    {
      int& v =
        o.request_flag;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.request_flag_value,
        i.request_flag_null);
    }
  }

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  access::object_traits_impl< ::TelemPoint, id_sqlite >::map_type*
  access::object_traits_impl< ::TelemPoint, id_sqlite >::map;

  const access::object_traits_impl< ::TelemPoint, id_sqlite >::info_type
  access::object_traits_impl< ::TelemPoint, id_sqlite >::info (
    typeid (::TelemPoint),
    0,
    0,
    "TelemPoint",
    &odb::create_impl< ::TelemPoint >,
    &odb::dispatch_impl< ::TelemPoint, id_sqlite >,
    0);

  static const access::object_traits_impl< ::TelemPoint, id_sqlite >::entry_type
  polymorphic_entry_for_TelemPoint;

  const char access::object_traits_impl< ::TelemPoint, id_sqlite >::persist_statement[] =
  "INSERT INTO \"TelemPoint\" "
  "(\"id\", "
  "\"typeid\", "
  "\"name\", "
  "\"register_address\", "
  "\"data_type\", "
  "\"value_type\", "
  "\"bool_value\", "
  "\"int_value\", "
  "\"float_value\", "
  "\"timestamp\", "
  "\"unit\", "
  "\"request_flag\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::TelemPoint, id_sqlite >::find_statement[] =
  "SELECT "
  "\"TelemPoint\".\"id\", "
  "\"TelemPoint\".\"typeid\", "
  "\"TelemPoint\".\"name\", "
  "\"TelemPoint\".\"register_address\", "
  "\"TelemPoint\".\"data_type\", "
  "\"TelemPoint\".\"value_type\", "
  "\"TelemPoint\".\"bool_value\", "
  "\"TelemPoint\".\"int_value\", "
  "\"TelemPoint\".\"float_value\", "
  "\"TelemPoint\".\"timestamp\", "
  "\"TelemPoint\".\"unit\", "
  "\"TelemPoint\".\"request_flag\" "
  "FROM \"TelemPoint\" "
  "WHERE \"TelemPoint\".\"id\"=?";

  const char access::object_traits_impl< ::TelemPoint, id_sqlite >::
  find_discriminator_statement[] =
  "SELECT "
  "\"TelemPoint\".\"typeid\" "
  "FROM \"TelemPoint\" "
  "WHERE \"TelemPoint\".\"id\"=?";

  const char access::object_traits_impl< ::TelemPoint, id_sqlite >::update_statement[] =
  "UPDATE \"TelemPoint\" "
  "SET "
  "\"name\"=?, "
  "\"register_address\"=?, "
  "\"data_type\"=?, "
  "\"value_type\"=?, "
  "\"bool_value\"=?, "
  "\"int_value\"=?, "
  "\"float_value\"=?, "
  "\"timestamp\"=?, "
  "\"unit\"=?, "
  "\"request_flag\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::TelemPoint, id_sqlite >::erase_statement[] =
  "DELETE FROM \"TelemPoint\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::TelemPoint, id_sqlite >::query_statement[] =
  "SELECT "
  "\"TelemPoint\".\"id\", "
  "\"TelemPoint\".\"typeid\", "
  "\"TelemPoint\".\"name\", "
  "\"TelemPoint\".\"register_address\", "
  "\"TelemPoint\".\"data_type\", "
  "\"TelemPoint\".\"value_type\", "
  "\"TelemPoint\".\"bool_value\", "
  "\"TelemPoint\".\"int_value\", "
  "\"TelemPoint\".\"float_value\", "
  "\"TelemPoint\".\"timestamp\", "
  "\"TelemPoint\".\"unit\", "
  "\"TelemPoint\".\"request_flag\" "
  "FROM \"TelemPoint\"";

  const char access::object_traits_impl< ::TelemPoint, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"TelemPoint\"";

  const char access::object_traits_impl< ::TelemPoint, id_sqlite >::table_name[] =
  "\"TelemPoint\"";

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  persist (database& db, object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (top);

    using namespace sqlite;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_persist, db, &obj, 0);
        return;
      }
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    if (top)
      callback (db,
                static_cast<const object_type&> (obj),
                callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    if (!top)
    {
      id_image_type& i (sts.id_image ());
      init (i, id (obj));

      binding& idb (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || idb.version == 0)
      {
        bind (idb.bind, i);
        sts.id_image_version (i.version);
        idb.version++;
      }
    }

    if (top)
      callback (db,
                static_cast<const object_type&> (obj),
                callback_event::post_persist);
  }

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  update (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    using namespace sqlite;
    using sqlite::update_statement;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_update, db, &obj, 0);
        return;
      }
    }

    if (top)
      callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    if (top)
    {
      callback (db, obj, callback_event::post_update);
      pointer_cache_traits::update (db, obj);
    }
  }

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  erase (database& db, const id_type& id, bool top, bool dyn)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (top);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    if (dyn)
    {
      discriminator_type d;
      root_traits::discriminator_ (sts.root_statements (), id, &d);

      if (d != info.discriminator)
      {
        const info_type& pi (root_traits::map->find (d));

        if (!pi.derived (info))
          throw object_not_persistent ();

        pi.dispatch (info_type::call_erase, db, 0, &id);
        return;
      }
    }

    if (top)
    {
      id_image_type& i (sts.id_image ());
      init (i, id);

      binding& idb (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || idb.version == 0)
      {
        bind (idb.bind, i);
        sts.id_image_version (i.version);
        idb.version++;
      }
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    if (top)
      pointer_cache_traits::erase (db, id);
  }

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  erase (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_erase, db, &obj, 0);
        return;
      }
    }

    callback (db, obj, callback_event::pre_erase);
    erase (db, id (obj), true, false);
    callback (db, obj, callback_event::post_erase);
  }

  access::object_traits_impl< ::TelemPoint, id_sqlite >::pointer_type
  access::object_traits_impl< ::TelemPoint, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    root_traits::discriminator_type d;

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
      d = root_traits::discriminator (sts.image ());
    }
    else
      root_traits::discriminator_ (sts, id, &d);

    const info_type& pi (
      d == info.discriminator ? info : root_traits::map->find (d));

    pointer_type p (pi.create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback_event ce (callback_event::pre_load);
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);

      if (&pi != &info)
      {
        std::size_t d (depth);
        pi.dispatch (info_type::call_load, db, &obj, &d);
      }

      sts.load_delayed (0);
      l.unlock ();
      ce = callback_event::post_load;
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position (), pi.delayed_loader);

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TelemPoint, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace sqlite;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        return pi.dispatch (info_type::call_find, db, &obj, &id);
      }
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TelemPoint, id_sqlite >::
  reload (database& db, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace sqlite;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        return pi.dispatch (info_type::call_reload, db, &obj, 0);
      }
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TelemPoint, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TelemPoint, id_sqlite >::
  discriminator_ (statements_type& sts,
                  const id_type& id,
                  discriminator_type* pd)
  {
    using namespace sqlite;

    id_image_type& idi (sts.discriminator_id_image ());
    init (idi, id);

    binding& idb (sts.discriminator_id_image_binding ());
    if (idi.version != sts.discriminator_id_image_version () ||
        idb.version == 0)
    {
      bind (idb.bind, idi);
      sts.discriminator_id_image_version (idi.version);
      idb.version++;
    }

    discriminator_image_type& i (sts.discriminator_image ());
    binding& imb (sts.discriminator_image_binding ());

    if (i.version != sts.discriminator_image_version () ||
        imb.version == 0)
    {
      sqlite::bind* b (imb.bind);
      std::size_t n (0);
      {
        b[n].type = sqlite::image_traits<
          ::std::string,
          sqlite::id_text>::bind_value;
        b[n].buffer = i.discriminator_value.data ();
        b[n].size = &i.discriminator_size;
        b[n].capacity = i.discriminator_value.capacity ();
        b[n].is_null = &i.discriminator_null;
      }

      sts.discriminator_image_version (i.version);
      imb.version++;
    }

    {
      select_statement& st (sts.find_discriminator_statement ());
      st.execute ();
      auto_result ar (st);
      select_statement::result r (st.fetch ());

      if (r == select_statement::no_data)
      {
        throw object_not_persistent ();
      }
      else if (r == select_statement::truncated)
      {
        bool grew (false);
        bool* t (sts.discriminator_image_truncated ());

        if (t[0UL])
        {
          i.discriminator_value.capacity (i.discriminator_size);
          grew = true;
        }

        if (grew)
          i.version++;

        if (i.version != sts.discriminator_image_version ())
        {
          sqlite::bind* b (imb.bind);
          std::size_t n (0);
          {
            b[n].type = sqlite::image_traits<
              ::std::string,
              sqlite::id_text>::bind_value;
            b[n].buffer = i.discriminator_value.data ();
            b[n].size = &i.discriminator_size;
            b[n].capacity = i.discriminator_value.capacity ();
            b[n].is_null = &i.discriminator_null;
          }

          sts.discriminator_image_version (i.version);
          imb.version++;
          st.refetch ();
        }
      }
    }

    if (pd != 0)
    {
      discriminator_type& d (*pd);
      {
        sqlite::value_traits<
            ::std::string,
            sqlite::id_text >::set_value (
          d,
          i.discriminator_value,
          i.discriminator_size,
          i.discriminator_null);
      }
    }
  }

  result< access::object_traits_impl< ::TelemPoint, id_sqlite >::object_type >
  access::object_traits_impl< ::TelemPoint, id_sqlite >::
  query (database& db, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::polymorphic_object_result_impl<object_type> > r (
      new (shared) sqlite::polymorphic_object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TelemPoint, id_sqlite >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // MasterPoint
  //

  struct access::object_traits_impl< ::MasterPoint, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  bool access::object_traits_impl< ::MasterPoint, id_sqlite >::
  grow (image_type& i,
        bool* t,
        std::size_t d)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // TelemPoint base
    //
    if (--d != 0)
    {
      if (base_traits::grow (*i.base, t + 2UL))
        i.base->version++;
    }

    // rw_flag
    //
    t[0UL] = false;

    // return_flag
    //
    t[1UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  bind (sqlite::bind* b,
        const sqlite::bind* id,
        std::size_t id_size,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // id
    //
    if (sk == statement_insert)
    {
      if (id != 0)
        std::memcpy (&b[n], id, id_size * sizeof (id[0]));
      n += id_size;
    }

    // rw_flag
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.rw_flag_value;
    b[n].is_null = &i.rw_flag_null;
    n++;

    // return_flag
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.return_flag_value;
    b[n].is_null = &i.return_flag_null;
    n++;

    // id
    //
    if (sk == statement_update)
    {
      if (id != 0)
        std::memcpy (&b[n], id, id_size * sizeof (id[0]));
      n += id_size;
    }

    // TelemPoint base
    //
    if (sk == statement_select)
      base_traits::bind (b + n, *i.base, sk);
  }

  bool access::object_traits_impl< ::MasterPoint, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // rw_flag
    //
    {
      int const& v =
        o.rw_flag;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.rw_flag_value,
        is_null,
        v);
      i.rw_flag_null = is_null;
    }

    // return_flag
    //
    {
      int const& v =
        o.return_flag;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.return_flag_value,
        is_null,
        v);
      i.return_flag_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db,
        std::size_t d)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // TelemPoint base
    //
    if (--d != 0)
      base_traits::init (o, *i.base, db);

    // rw_flag
    //
    {
      int& v =
        o.rw_flag;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.rw_flag_value,
        i.rw_flag_null);
    }

    // return_flag
    //
    {
      int& v =
        o.return_flag;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.return_flag_value,
        i.return_flag_null);
    }
  }

  const access::object_traits_impl< ::MasterPoint, id_sqlite >::info_type
  access::object_traits_impl< ::MasterPoint, id_sqlite >::info (
    typeid (::MasterPoint),
    &object_traits_impl< ::TelemPoint, id_sqlite >::info,
    0,
    "MasterPoint",
    &odb::create_impl< ::MasterPoint >,
    &odb::dispatch_impl< ::MasterPoint, id_sqlite >,
    &statements_type::delayed_loader);

  static const access::object_traits_impl< ::MasterPoint, id_sqlite >::entry_type
  polymorphic_entry_for_MasterPoint;

  const char access::object_traits_impl< ::MasterPoint, id_sqlite >::persist_statement[] =
  "INSERT INTO \"MasterPoint\" "
  "(\"id\", "
  "\"rw_flag\", "
  "\"return_flag\") "
  "VALUES "
  "(?, ?, ?)";

  const char* const access::object_traits_impl< ::MasterPoint, id_sqlite >::find_statements[] =
  {
    "SELECT "
    "\"MasterPoint\".\"rw_flag\", "
    "\"MasterPoint\".\"return_flag\", "
    "\"TelemPoint\".\"id\", "
    "\"TelemPoint\".\"typeid\", "
    "\"TelemPoint\".\"name\", "
    "\"TelemPoint\".\"register_address\", "
    "\"TelemPoint\".\"data_type\", "
    "\"TelemPoint\".\"value_type\", "
    "\"TelemPoint\".\"bool_value\", "
    "\"TelemPoint\".\"int_value\", "
    "\"TelemPoint\".\"float_value\", "
    "\"TelemPoint\".\"timestamp\", "
    "\"TelemPoint\".\"unit\", "
    "\"TelemPoint\".\"request_flag\" "
    "FROM \"MasterPoint\" "
    "LEFT JOIN \"TelemPoint\" ON \"TelemPoint\".\"id\"=\"MasterPoint\".\"id\" "
    "WHERE \"MasterPoint\".\"id\"=?",

    "SELECT "
    "\"MasterPoint\".\"rw_flag\", "
    "\"MasterPoint\".\"return_flag\" "
    "FROM \"MasterPoint\" "
    "WHERE \"MasterPoint\".\"id\"=?"
  };

  const std::size_t access::object_traits_impl< ::MasterPoint, id_sqlite >::find_column_counts[] =
  {
    14UL,
    2UL
  };

  const char access::object_traits_impl< ::MasterPoint, id_sqlite >::update_statement[] =
  "UPDATE \"MasterPoint\" "
  "SET "
  "\"rw_flag\"=?, "
  "\"return_flag\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::MasterPoint, id_sqlite >::erase_statement[] =
  "DELETE FROM \"MasterPoint\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::MasterPoint, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"MasterPoint\".\"rw_flag\",\n"
  "\"MasterPoint\".\"return_flag\",\n"
  "\"TelemPoint\".\"id\",\n"
  "\"TelemPoint\".\"typeid\",\n"
  "\"TelemPoint\".\"name\",\n"
  "\"TelemPoint\".\"register_address\",\n"
  "\"TelemPoint\".\"data_type\",\n"
  "\"TelemPoint\".\"value_type\",\n"
  "\"TelemPoint\".\"bool_value\",\n"
  "\"TelemPoint\".\"int_value\",\n"
  "\"TelemPoint\".\"float_value\",\n"
  "\"TelemPoint\".\"timestamp\",\n"
  "\"TelemPoint\".\"unit\",\n"
  "\"TelemPoint\".\"request_flag\"\n"
  "FROM \"MasterPoint\"\n"
  "LEFT JOIN \"TelemPoint\" ON \"TelemPoint\".\"id\"=\"MasterPoint\".\"id\"";

  const char access::object_traits_impl< ::MasterPoint, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"MasterPoint\"";

  const char access::object_traits_impl< ::MasterPoint, id_sqlite >::table_name[] =
  "\"MasterPoint\"";

  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  persist (database& db, object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (top);

    using namespace sqlite;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_persist, db, &obj, 0);
        return;
      }
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    if (top)
      callback (db,
                static_cast<const object_type&> (obj),
                callback_event::pre_persist);

    base_traits::persist (db, obj, false, false);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());
    const binding& idb (sts.id_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (idb.version != sts.insert_id_binding_version () ||
        im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, idb.bind, idb.count, im, statement_insert);
      sts.insert_id_binding_version (idb.version);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    if (top)
      callback (db,
                static_cast<const object_type&> (obj),
                callback_event::post_persist);
  }

  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  update (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    using namespace sqlite;
    using sqlite::update_statement;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_update, db, &obj, 0);
        return;
      }
    }

    if (top)
      callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    base_traits::update (db, obj, false, false);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    const binding& idb (sts.id_image_binding ());
    binding& imb (sts.update_image_binding ());
    if (idb.version != sts.update_id_binding_version () ||
        im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, idb.bind, idb.count, im, statement_update);
      sts.update_id_binding_version (idb.version);
      sts.update_image_version (im.version);
      imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    if (top)
    {
      callback (db, obj, callback_event::post_update);
      pointer_cache_traits::update (db, obj);
    }
  }

  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  erase (database& db, const id_type& id, bool top, bool dyn)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (top);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    if (dyn)
    {
      discriminator_type d;
      root_traits::discriminator_ (sts.root_statements (), id, &d);

      if (d != info.discriminator)
      {
        const info_type& pi (root_traits::map->find (d));

        if (!pi.derived (info))
          throw object_not_persistent ();

        pi.dispatch (info_type::call_erase, db, 0, &id);
        return;
      }
    }

    if (top)
    {
      id_image_type& i (sts.id_image ());
      init (i, id);

      binding& idb (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || idb.version == 0)
      {
        bind (idb.bind, i);
        sts.id_image_version (i.version);
        idb.version++;
      }
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    base_traits::erase (db, id, false, false);

    if (top)
      pointer_cache_traits::erase (db, id);
  }

  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  erase (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_erase, db, &obj, 0);
        return;
      }
    }

    callback (db, obj, callback_event::pre_erase);
    erase (db, id (obj), true, false);
    callback (db, obj, callback_event::post_erase);
  }

  access::object_traits_impl< ::MasterPoint, id_sqlite >::pointer_type
  access::object_traits_impl< ::MasterPoint, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      root_traits::pointer_type rp (pointer_cache_traits::find (db, id));

      if (!root_traits::pointer_traits::null_ptr (rp))
        return
          root_traits::pointer_traits::dynamic_pointer_cast<object_type> (rp);
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());
    root_statements_type& rsts (sts.root_statements ());

    statements_type::auto_lock l (rsts);
    root_traits::discriminator_type d;

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
      d = root_traits::discriminator (rsts.image ());
    }
    else
      root_traits::discriminator_ (rsts, id, &d);

    const info_type& pi (
      d == info.discriminator ? info : root_traits::map->find (d));

    root_traits::pointer_type rp (pi.create ());
    pointer_type p (
      root_traits::pointer_traits::static_pointer_cast<object_type> (rp));
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, rp));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement (depth));
      ODB_POTENTIALLY_UNUSED (st);

      callback_event ce (callback_event::pre_load);
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);

      if (&pi != &info)
      {
        std::size_t d (depth);
        pi.dispatch (info_type::call_load, db, &obj, &d);
      }

      rsts.load_delayed (0);
      l.unlock ();
      ce = callback_event::post_load;
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      pointer_cache_traits::load (ig.position ());
    }
    else
      rsts.delay_load (id, obj, ig.position (), pi.delayed_loader);

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::MasterPoint, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace sqlite;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        return pi.dispatch (info_type::call_find, db, &obj, &id);
      }
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());
    root_statements_type& rsts (sts.root_statements ());

    statements_type::auto_lock l (rsts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement (depth));
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    rsts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::MasterPoint, id_sqlite >::
  reload (database& db, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace sqlite;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        return pi.dispatch (info_type::call_reload, db, &obj, 0);
      }
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());
    root_statements_type& rsts (sts.root_statements ());

    statements_type::auto_lock l (rsts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement (depth));
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    rsts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::MasterPoint, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id,
         std::size_t d)
  {
    using namespace sqlite;

    if (d == depth)
    {
      id_image_type& i (sts.id_image ());
      init (i, *id);

      binding& idb (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || idb.version == 0)
      {
        bind (idb.bind, i);
        sts.id_image_version (i.version);
        idb.version++;
      }
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding (d));

    if (imb.version == 0 ||
        check_version (sts.select_image_versions (), im))
    {
      bind (imb.bind, 0, 0, im, statement_select);
      update_version (sts.select_image_versions (),
                      im,
                      sts.select_image_bindings ());
    }

    select_statement& st (sts.find_statement (d));

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated (), d))
        im.version++;

      if (check_version (sts.select_image_versions (), im))
      {
        bind (imb.bind, 0, 0, im, statement_select);
        update_version (sts.select_image_versions (),
                        im,
                        sts.select_image_bindings ());
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload,
         std::size_t d)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    if (--d != 0)
      base_traits::load_ (sts.base_statements (), obj, reload);
  }

  void access::object_traits_impl< ::MasterPoint, id_sqlite >::
  load_ (database& db, root_type& r, std::size_t d)
  {
    using namespace sqlite;

    object_type& obj (static_cast<object_type&> (r));
    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    d = depth - d;

    if (!find_ (sts, 0, d))
      throw object_not_persistent ();

    select_statement& st (sts.find_statement (d));
    ODB_POTENTIALLY_UNUSED (st);

    init (obj, sts.image (), &db, d);
    load_ (sts, obj, false, d);
  }

  result< access::object_traits_impl< ::MasterPoint, id_sqlite >::object_type >
  access::object_traits_impl< ::MasterPoint, id_sqlite >::
  query (database& db, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding (depth));

    if (imb.version == 0 ||
        check_version (sts.select_image_versions (), im))
    {
      bind (imb.bind, 0, 0, im, statement_select);
      update_version (sts.select_image_versions (),
                      im,
                      sts.select_image_bindings ());
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::polymorphic_object_result_impl<object_type> > r (
      new (shared) sqlite::polymorphic_object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::MasterPoint, id_sqlite >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // SlavePoint
  //

  const char alias_traits<  ::TelemPoint,
    id_sqlite,
    access::object_traits_impl< ::SlavePoint, id_sqlite >::base_tag>::
  table_name[] = "\"base_id_TelemPoint\"";

  struct access::object_traits_impl< ::SlavePoint, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::SlavePoint, id_sqlite >::id_type
  access::object_traits_impl< ::SlavePoint, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::SlavePoint, id_sqlite >::id_type
  access::object_traits_impl< ::SlavePoint, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::SlavePoint, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = false;

    // base
    //
    t[1UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // base
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.base_value;
    b[n].is_null = &i.base_null;
    n++;
  }

  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::SlavePoint, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      ::int64_t const& v =
        o.id;

      bool is_null (false);
      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        v);
      i.id_null = is_null;
    }

    // base
    //
    {
      ::std::shared_ptr< ::TelemPoint > const& v =
        o.base;

      typedef object_traits< ::TelemPoint > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::TelemPoint > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& ptr_id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i.base_value,
          is_null,
          ptr_id);
        i.base_null = is_null;
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      ::int64_t& v =
        o.id;

      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // base
    //
    {
      ::std::shared_ptr< ::TelemPoint >& v =
        o.base;

      typedef object_traits< ::TelemPoint > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::TelemPoint > > ptr_traits;

      if (i.base_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type ptr_id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          ptr_id,
          i.base_value,
          i.base_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (ptr_id));
      }
    }
  }

  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          ::int64_t,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::SlavePoint, id_sqlite >::persist_statement[] =
  "INSERT INTO \"SlavePoint\" "
  "(\"id\", "
  "\"base_id\") "
  "VALUES "
  "(?, ?)";

  const char access::object_traits_impl< ::SlavePoint, id_sqlite >::find_statement[] =
  "SELECT "
  "\"SlavePoint\".\"id\", "
  "\"SlavePoint\".\"base_id\" "
  "FROM \"SlavePoint\" "
  "WHERE \"SlavePoint\".\"id\"=?";

  const char access::object_traits_impl< ::SlavePoint, id_sqlite >::update_statement[] =
  "UPDATE \"SlavePoint\" "
  "SET "
  "\"base_id\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::SlavePoint, id_sqlite >::erase_statement[] =
  "DELETE FROM \"SlavePoint\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::SlavePoint, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"SlavePoint\".\"id\",\n"
  "\"SlavePoint\".\"base_id\"\n"
  "FROM \"SlavePoint\"\n"
  "LEFT JOIN \"TelemPoint\" AS \"base_id_TelemPoint\" ON \"base_id_TelemPoint\".\"id\"=\"SlavePoint\".\"base_id\"";

  const char access::object_traits_impl< ::SlavePoint, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"SlavePoint\"";

  const char access::object_traits_impl< ::SlavePoint, id_sqlite >::table_name[] =
  "\"SlavePoint\"";

  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::SlavePoint, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::SlavePoint, id_sqlite >::pointer_type
  access::object_traits_impl< ::SlavePoint, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::SlavePoint, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::SlavePoint, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::SlavePoint, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::SlavePoint, id_sqlite >::object_type >
  access::object_traits_impl< ::SlavePoint, id_sqlite >::
  query (database& db, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::SlavePoint, id_sqlite >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"SlavePoint\"");
          db.execute ("DROP TABLE IF EXISTS \"MasterPoint\"");
          db.execute ("DROP TABLE IF EXISTS \"TelemPoint\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"TelemPoint\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"typeid\" TEXT NOT NULL,\n"
                      "  \"name\" TEXT NOT NULL,\n"
                      "  \"register_address\" TEXT NOT NULL,\n"
                      "  \"data_type\" INT NOT NULL,\n"
                      "  \"value_type\" INT NOT NULL,\n"
                      "  \"bool_value\" INTEGER NOT NULL,\n"
                      "  \"int_value\" INTEGER NOT NULL,\n"
                      "  \"float_value\" REAL NOT NULL,\n"
                      "  \"timestamp\" INTEGER NOT NULL,\n"
                      "  \"unit\" TEXT NULL,\n"
                      "  \"request_flag\" INTEGER NOT NULL)");
          db.execute ("CREATE TABLE \"MasterPoint\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"rw_flag\" INTEGER NOT NULL,\n"
                      "  \"return_flag\" INTEGER NOT NULL,\n"
                      "  CONSTRAINT \"id_fk\"\n"
                      "    FOREIGN KEY (\"id\")\n"
                      "    REFERENCES \"TelemPoint\" (\"id\")\n"
                      "    ON DELETE CASCADE)");
          db.execute ("CREATE TABLE \"SlavePoint\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"base_id\" INTEGER NOT NULL,\n"
                      "  CONSTRAINT \"base_id_fk\"\n"
                      "    FOREIGN KEY (\"base_id\")\n"
                      "    REFERENCES \"TelemPoint\" (\"id\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
